apiVersion: apps/v1
kind: {{ .Values.blackbox.kind }}
metadata:
  name: {{ .Values.blackbox.name }}
  {{- with .Values.blackbox.labels }}
  labels:
    {{- toYaml .  | nindent 4 }}
  {{- end}}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.blackbox.replica }}
  selector:
    {{- with .Values.blackbox.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.blackbox.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end}}
    spec:
      containers:
        - name: {{ .Values.blackbox.name }}
          image: {{ .Values.blackbox.image}}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: {{ .Values.blackbox.port.number }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.blackbox.port.number }}
            timeoutSeconds: 5  
          ports:
            - containerPort: {{ .Values.blackbox.port.number }}




