apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blackbox.name }}
  namespace: {{ .Values.global.namespace}}
  labels:
    name: {{ .Values.blackbox.labels.app }}
spec:
  type: {{ .Values.blackbox.service.type }}
  ports:
    - port: {{ .Values.blackbox.service.port }}
      targetPort: {{ .Values.blackbox.port.number }}
      protocol: TCP
  selector:
    app: {{ .Values.blackbox.labels.app }}
