prometheus:
  name: prometheus 
  replica: 1
  kind: StatefulSet
  image: prom/prometheus:main
  serviceAccountName: prometheus 
  labels:
    component: collector
    name: prometheus
  volumeMounts:
    name: prometheus-config
    mountPath: /etc/prometheus/prometheus.yml
    subPath: prometheus.yml
  volume: 
    config: prometheus-config
    data: prometheus-data
  configMap:
    name: prometheus-config
  ClusterRole:
    name: prometheus-cr
  ClusterRoleBinding:
    name: prometheus-crb
  port: 
    name: prometheus
    number: 9090
  service:
    name: prometheus
    type: ClusterIP
    port: 9090
  sc:
    name: prometheus 
  resources:
    requests:
      cpu: 0.1
      memory: 200Mi
    limits:
      cpu: 0.5
      memory: 500Mi
  pvc:
    name: prometheus 
    size: 5Gi
