apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name}}
  namespace: {{ .Values.namespace }}
  {{- with .Values.grafana.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}   

spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    {{- with .Values.grafana.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end}}
  template:
    metadata:
#      {{- with .Values.podAnnotations }}
#      annotations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
      {{- with .Values.grafana.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end}}
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        supplementalGroups:
          - 0
      containers:
        - name: {{ .Values.grafana.name }}
          image: {{ .Values.grafana.image }}
          securityContext:
            allowPrivilegeEscalation: false            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.grafana.ports.name }}
              containerPort: {{ .Values.grafana.ports.port }}
              protocol: TCP
          volumeMounts:
          {{- if eq .Values.env.local false }}
          - name: {{ .Values.grafana.sc.name}}
            mountPath: /var/lib/grafana
          {{- end }}
          - name: datasource
            mountPath: /etc/grafana/provisioning/datasources
          - name: dashboard
            mountPath: /etc/grafana/provisioning/dashboards
#          {{- if .Values.env.aws }}
#          - name: credential
#            mountPath: /usr/share/grafana/.aws/
#            subPath: credentials
#          {{- end }}            

      volumes:
        - name: datasource
          configMap:
            name: {{ .Values.grafana.configmap.name}}
            items:
              - key: datasource
                path: datasource.yml
        - name: dashboard
          configMap:
            name: {{ .Values.grafana.configmap.name}}
            items:
              - key: dashboard.json
                path: dashboard.json
              - key: dashboard
                path: dashboard.yml
        - name: credential
          configMap:
            name: {{ .Values.grafana.configmap.name}}
            items:
              {{- if eq .Values.env.aws true }}
              - key: credentials
                path: credentials 
              {{- end }}
        {{- if eq .Values.env.local false }}
        - name: {{ .Values.grafana.sc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.pvc.name }}
        {{- end }}


              
            
 #         livenessProbe:
 #           httpGet:
 #             path: /
 #             port: http
 #         readinessProbe:
 #           httpGet:
 #             path: /
 #             port: http


#       - ./monitor/grafana.ini:/etc/grafana/grafana.ini
 #     - ./monitor/dashboard.json:/etc/dashboard.json
#      - ./monitor/provision.yml:/etc/grafana/provisioning/datasources/datasource.yml
#      - ./monitor/dashboards/:/etc/grafana/provisioning/dashboards/
