#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: {{ .Values.grafana.sc.name }}
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.grafana.sc.name}}
#provisioner: kubernetes.io/aws-ebs
provisioner: kubernetes.io/{{ .Values.global.pv.provisioner}}
parameters:
  type: io1
  iopsPerGB: "2"
  fsType: ext4
